apiVersion: v1
kind: Pod
metadata:
  labels:
    app: readpod
  name: readpod
  namespace: storage-test
spec:
  containers:
  - args:
    - ls -latr /tmp/psdisk/; sleep 9999
    command:
    - bin/bash
    - -c
    image: centos:7
    name: shell
    volumeMounts:
    - mountPath: /tmp/psdisk
      name: mypd
  volumes:
  - name: mypd
    persistentVolumeClaim:
      claimName: psdisk

