apiVersion: v1
kind: Pod
metadata:
  labels:
    app: writepod
  name: writepod
  namespace: storage-test
spec:
  containers:
  - args:
    - for i in {1..4}; do echo $i; dd if=/dev/urandom of=/tmp/psdisk/1GB.bin bs=64M count=4 iflag=fullblock; done
    command:
    - bin/bash
    - -c
    image: centos:7
    name: shell
    volumeMounts:
    - mountPath: /tmp/psdisk
      name: mypd
  volumes:
  - name: mypd
    persistentVolumeClaim:
      claimName: psdisk

